import 'package:flutter/material.dart';

class ZodiacCharacter {
  final String name;
  final String emoji;
  final String englishName;
  final Color primaryColor;
  final Color secondaryColor;
  final String description;
  final String personality;
  final String fortune;
  final String compatibility;
  final String luckyNumbers;
  final String luckyColors;
  final String luckyDirections;
  final String element;
  final String season;
  final String timeRange;
  final List<String> traits;
  final List<String> strengths;
  final List<String> weaknesses;

  const ZodiacCharacter({
    required this.name,
    required this.emoji,
    required this.englishName,
    required this.primaryColor,
    required this.secondaryColor,
    required this.description,
    required this.personality,
    required this.fortune,
    required this.compatibility,
    required this.luckyNumbers,
    required this.luckyColors,
    required this.luckyDirections,
    required this.element,
    required this.season,
    required this.timeRange,
    required this.traits,
    required this.strengths,
    required this.weaknesses,
  });
}

class ZodiacCharacters {
  static const List<ZodiacCharacter> characters = [
    ZodiacCharacter(
      name: '쥐',
      emoji: '🐭',
      englishName: 'Rat',
      primaryColor: Color(0xFF8B5CF6),
      secondaryColor: Color(0xFF7C3AED),
      description: '쥐띠는 지혜롭고 적응력이 뛰어나며, 기회를 잘 포착하는 능력이 있습니다.',
      personality: '쥐띠는 똑똑하고 현실적이며, 위기 상황에서도 침착함을 유지합니다. 새로운 환경에 빠르게 적응하며, 사람들과의 관계를 중요하게 생각합니다.',
      fortune: '쥐띠는 재물운이 좋고, 새로운 사업이나 투자에서 성공할 가능성이 높습니다. 특히 30대 후반부터 운이 상승합니다.',
      compatibility: '용띠, 원숭이띠, 소띠와 잘 맞습니다.',
      luckyNumbers: '2, 3, 6, 8',
      luckyColors: '파란색, 금색, 은색',
      luckyDirections: '북쪽, 서쪽',
      element: '水 (물)',
      season: '겨울',
      timeRange: '23:00-01:00',
      traits: ['지혜로움', '적응력', '기회 포착', '현실적'],
      strengths: ['빠른 판단력', '좋은 기억력', '사교성', '경제적 감각'],
      weaknesses: ['과도한 걱정', '완벽주의', '경쟁심'],
    ),
    ZodiacCharacter(
      name: '소',
      emoji: '🐮',
      englishName: 'Ox',
      primaryColor: Color(0xFF059669),
      secondaryColor: Color(0xFF047857),
      description: '소띠는 성실하고 끈기 있으며, 안정적인 삶을 추구합니다.',
      personality: '소띠는 신중하고 책임감이 강하며, 한번 시작한 일은 끝까지 해내는 강인한 의지를 가지고 있습니다.',
      fortune: '소띠는 꾸준한 노력으로 큰 성과를 얻을 수 있습니다. 특히 부동산이나 장기 투자에서 좋은 결과를 얻을 수 있습니다.',
      compatibility: '뱀띠, 닭띠, 쥐띠와 잘 맞습니다.',
      luckyNumbers: '1, 4, 6, 9',
      luckyColors: '초록색, 노란색',
      luckyDirections: '동남쪽',
      element: '土 (흙)',
      season: '겨울',
      timeRange: '01:00-03:00',
      traits: ['성실함', '끈기', '안정성', '책임감'],
      strengths: ['꾸준함', '신뢰성', '실용성', '인내심'],
      weaknesses: ['고집', '변화 거부', '표현 부족'],
    ),
    ZodiacCharacter(
      name: '호랑이',
      emoji: '🐯',
      englishName: 'Tiger',
      primaryColor: Color(0xFFDC2626),
      secondaryColor: Color(0xFFB91C1C),
      description: '호랑이띠는 용맹하고 리더십이 강하며, 모험을 즐깁니다.',
      personality: '호랑이띠는 자신감이 넘치고 도전정신이 강하며, 정의감이 뛰어납니다. 새로운 일에 대한 열정이 많습니다.',
      fortune: '호랑이띠는 리더십을 발휘할 수 있는 분야에서 성공할 가능성이 높습니다. 특히 40대에 큰 전환점을 맞을 수 있습니다.',
      compatibility: '말띠, 개띠, 돼지띠와 잘 맞습니다.',
      luckyNumbers: '1, 3, 4, 7',
      luckyColors: '빨간색, 주황색',
      luckyDirections: '동쪽, 남쪽',
      element: '木 (나무)',
      season: '봄',
      timeRange: '03:00-05:00',
      traits: ['용맹함', '리더십', '모험심', '정의감'],
      strengths: ['자신감', '결단력', '열정', '카리스마'],
      weaknesses: ['성급함', '고집', '경쟁심'],
    ),
    ZodiacCharacter(
      name: '토끼',
      emoji: '🐰',
      englishName: 'Rabbit',
      primaryColor: Color(0xFFF59E0B),
      secondaryColor: Color(0xFFD97706),
      description: '토끼띠는 온화하고 예술적이며, 평화를 사랑합니다.',
      personality: '토끼띠는 섬세하고 예민하며, 아름다운 것을 좋아합니다. 갈등을 피하고 조화로운 관계를 추구합니다.',
      fortune: '토끼띠는 예술이나 창작 분야에서 성공할 가능성이 높습니다. 특히 20대 후반부터 운이 상승합니다.',
      compatibility: '양띠, 돼지띠, 개띠와 잘 맞습니다.',
      luckyNumbers: '3, 4, 6, 9',
      luckyColors: '분홍색, 연두색',
      luckyDirections: '동쪽',
      element: '木 (나무)',
      season: '봄',
      timeRange: '05:00-07:00',
      traits: ['온화함', '예술성', '평화주의', '섬세함'],
      strengths: ['예술적 감각', '섬세함', '인간관계', '직관력'],
      weaknesses: ['우유부단', '예민함', '갈등 회피'],
    ),
    ZodiacCharacter(
      name: '용',
      emoji: '🐲',
      englishName: 'Dragon',
      primaryColor: Color(0xFF7C2D12),
      secondaryColor: Color(0xFF92400E),
      description: '용띠는 강력하고 영감을 주며, 큰 꿈을 가지고 있습니다.',
      personality: '용띠는 자신감이 넘치고 야심적이며, 다른 사람들에게 영감을 주는 능력이 있습니다. 독립적이고 자유로운 성격입니다.',
      fortune: '용띠는 큰 사업이나 프로젝트에서 성공할 가능성이 높습니다. 특히 30대에 큰 기회를 잡을 수 있습니다.',
      compatibility: '쥐띠, 원숭이띠, 닭띠와 잘 맞습니다.',
      luckyNumbers: '1, 6, 7, 8',
      luckyColors: '금색, 은색',
      luckyDirections: '동쪽, 서쪽',
      element: '土 (흙)',
      season: '봄',
      timeRange: '07:00-09:00',
      traits: ['강력함', '영감', '야심', '독립성'],
      strengths: ['리더십', '창의성', '자신감', '영감력'],
      weaknesses: ['고집', '완벽주의', '독선적'],
    ),
    ZodiacCharacter(
      name: '뱀',
      emoji: '🐍',
      englishName: 'Snake',
      primaryColor: Color(0xFF059669),
      secondaryColor: Color(0xFF047857),
      description: '뱀띠는 지혜롭고 신비로우며, 깊이 있는 사고를 합니다.',
      personality: '뱀띠는 직관력이 뛰어나고 신중하며, 내면의 깊이가 있습니다. 예술적 감각이 뛰어나고 철학적 사고를 합니다.',
      fortune: '뱀띠는 지혜와 직관을 활용한 분야에서 성공할 수 있습니다. 특히 40대 후반부터 운이 상승합니다.',
      compatibility: '소띠, 닭띠, 원숭이띠와 잘 맞습니다.',
      luckyNumbers: '2, 8, 9',
      luckyColors: '빨간색, 검은색',
      luckyDirections: '남동쪽',
      element: '火 (불)',
      season: '여름',
      timeRange: '09:00-11:00',
      traits: ['지혜', '신비로움', '직관력', '신중함'],
      strengths: ['직관력', '예술성', '철학적 사고', '집중력'],
      weaknesses: ['의심', '은둔성', '완벽주의'],
    ),
    ZodiacCharacter(
      name: '말',
      emoji: '🐴',
      englishName: 'Horse',
      primaryColor: Color(0xFFDC2626),
      secondaryColor: Color(0xFFB91C1C),
      description: '말띠는 자유롭고 활발하며, 모험을 즐깁니다.',
      personality: '말띠는 에너지가 넘치고 자유로운 영혼을 가지고 있습니다. 새로운 경험을 추구하고 여행을 좋아합니다.',
      fortune: '말띠는 자유로운 환경에서 성공할 수 있습니다. 특히 해외나 여행 관련 사업에서 좋은 결과를 얻을 수 있습니다.',
      compatibility: '호랑이띠, 개띠, 양띠와 잘 맞습니다.',
      luckyNumbers: '2, 3, 7, 8',
      luckyColors: '빨간색, 노란색',
      luckyDirections: '남쪽',
      element: '火 (불)',
      season: '여름',
      timeRange: '11:00-13:00',
      traits: ['자유로움', '활발함', '모험심', '에너지'],
      strengths: ['활동성', '적응력', '열정', '사교성'],
      weaknesses: ['성급함', '집중력 부족', '변덕'],
    ),
    ZodiacCharacter(
      name: '양',
      emoji: '🐑',
      englishName: 'Goat',
      primaryColor: Color(0xFFF59E0B),
      secondaryColor: Color(0xFFD97706),
      description: '양띠는 온화하고 예술적이며, 창의적입니다.',
      personality: '양띠는 상상력이 풍부하고 예술적 감각이 뛰어납니다. 다른 사람들을 배려하고 조화를 추구합니다.',
      fortune: '양띠는 예술이나 창작 분야에서 성공할 가능성이 높습니다. 특히 30대 중반부터 운이 상승합니다.',
      compatibility: '토끼띠, 돼지띠, 말띠와 잘 맞습니다.',
      luckyNumbers: '2, 7, 8, 9',
      luckyColors: '초록색, 빨간색',
      luckyDirections: '남서쪽',
      element: '土 (흙)',
      season: '여름',
      timeRange: '13:00-15:00',
      traits: ['온화함', '예술성', '창의성', '배려심'],
      strengths: ['상상력', '예술적 감각', '인간관계', '직관력'],
      weaknesses: ['우유부단', '의존성', '현실성 부족'],
    ),
    ZodiacCharacter(
      name: '원숭이',
      emoji: '🐵',
      englishName: 'Monkey',
      primaryColor: Color(0xFF7C2D12),
      secondaryColor: Color(0xFF92400E),
      description: '원숭이띠는 똑똑하고 재치 있으며, 문제 해결 능력이 뛰어납니다.',
      personality: '원숭이띠는 지능이 높고 유머 감각이 있으며, 새로운 기술을 빠르게 습득합니다. 호기심이 많고 적응력이 뛰어납니다.',
      fortune: '원숭이띠는 기술이나 IT 분야에서 성공할 가능성이 높습니다. 특히 20대부터 운이 상승합니다.',
      compatibility: '쥐띠, 용띠, 뱀띠와 잘 맞습니다.',
      luckyNumbers: '4, 9',
      luckyColors: '흰색, 파란색',
      luckyDirections: '서쪽',
      element: '金 (금)',
      season: '가을',
      timeRange: '15:00-17:00',
      traits: ['지능', '재치', '문제해결', '적응력'],
      strengths: ['학습능력', '유머감각', '기술적 재능', '호기심'],
      weaknesses: ['산만함', '집중력 부족', '변덕'],
    ),
    ZodiacCharacter(
      name: '닭',
      emoji: '🐓',
      englishName: 'Rooster',
      primaryColor: Color(0xFFF59E0B),
      secondaryColor: Color(0xFFD97706),
      description: '닭띠는 정확하고 체계적이며, 시간을 중요하게 생각합니다.',
      personality: '닭띠는 완벽주의적이고 체계적이며, 시간 관리에 뛰어납니다. 자신의 의견을 명확히 표현하고 책임감이 강합니다.',
      fortune: '닭띠는 체계적인 계획을 세워 성공할 수 있습니다. 특히 50대부터 운이 상승합니다.',
      compatibility: '소띠, 뱀띠, 용띠와 잘 맞습니다.',
      luckyNumbers: '5, 7, 8, 12',
      luckyColors: '금색, 갈색',
      luckyDirections: '서쪽',
      element: '金 (금)',
      season: '가을',
      timeRange: '17:00-19:00',
      traits: ['정확함', '체계적', '시간관리', '완벽주의'],
      strengths: ['계획성', '책임감', '정확성', '표현력'],
      weaknesses: ['비판적', '완벽주의', '고집'],
    ),
    ZodiacCharacter(
      name: '개',
      emoji: '🐕',
      englishName: 'Dog',
      primaryColor: Color(0xFF059669),
      secondaryColor: Color(0xFF047857),
      description: '개띠는 충성스럽고 정직하며, 정의감이 강합니다.',
      personality: '개띠는 신뢰할 수 있고 정직하며, 친구들을 위해 희생할 줄 압니다. 공정하고 정의로운 성격을 가지고 있습니다.',
      fortune: '개띠는 신뢰를 바탕으로 한 관계에서 성공할 수 있습니다. 특히 40대부터 운이 상승합니다.',
      compatibility: '호랑이띠, 말띠, 토끼띠와 잘 맞습니다.',
      luckyNumbers: '3, 4, 9, 11',
      luckyColors: '초록색, 빨간색',
      luckyDirections: '북동쪽',
      element: '土 (흙)',
      season: '가을',
      timeRange: '19:00-21:00',
      traits: ['충성심', '정직함', '정의감', '신뢰성'],
      strengths: ['신뢰성', '정의감', '친구관계', '책임감'],
      weaknesses: ['의심', '완벽주의', '비관적'],
    ),
    ZodiacCharacter(
      name: '돼지',
      emoji: '🐷',
      englishName: 'Pig',
      primaryColor: Color(0xFFEC4899),
      secondaryColor: Color(0xFFDB2777),
      description: '돼지띠는 순수하고 관대하며, 즐거운 삶을 추구합니다.',
      personality: '돼지띠는 마음이 넓고 관대하며, 다른 사람들을 잘 도와줍니다. 즐거운 것을 좋아하고 긍정적인 성격을 가지고 있습니다.',
      fortune: '돼지띠는 관대한 마음으로 인해 좋은 인맥을 형성하고 성공할 수 있습니다. 특히 60대부터 운이 상승합니다.',
      compatibility: '토끼띠, 양띠, 호랑이띠와 잘 맞습니다.',
      luckyNumbers: '2, 5, 8, 9',
      luckyColors: '분홍색, 회색',
      luckyDirections: '북서쪽',
      element: '水 (물)',
      season: '겨울',
      timeRange: '21:00-23:00',
      traits: ['순수함', '관대함', '즐거움', '긍정성'],
      strengths: ['관대함', '인간관계', '긍정성', '도움'],
      weaknesses: ['순진함', '과신', '계획성 부족'],
    ),
  ];

  static ZodiacCharacter getCharacterByYear(int year) {
    // 12지신은 12년 주기로 반복됩니다
    final index = (year - 4) % 12;
    return characters[index];
  }

  static ZodiacCharacter getCharacterByName(String name) {
    return characters.firstWhere(
      (character) => character.name == name,
      orElse: () => characters.first,
    );
  }
}


